ALTER TABLE "barbershops"
  ADD COLUMN IF NOT EXISTS "queueAlertEnabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "queueAlertThreshold" INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS "queueAlertPhone" VARCHAR(20),
  ADD COLUMN IF NOT EXISTS "queueAlertUpdatedAt" TIMESTAMP(3);
